---
exclude_paths:
- test/*
- docs/*
- examples/*
- vendor/*
ratings:
  paths:
  - "**.php"
engines:
  phpmd:
    enabled: true
    checks:
      Naming/LongVariable:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Design/WeightedMethodCount:
        enabled: false
      Design/TooManyMethods:
        enabled: false
  phpcodesniffer:
    enabled: true
