# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

before_script:
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --configuration phpunit.travis.xml --coverage-clover build/logs/clover.xml

after_success:
    - php vendor/bin/coveralls -v

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"